added ability to ignore channels
yugecin/tsstats pull request #15
Opened 2018-02-15 14:45 UTC by Wunderharke

added ability to ignore channels via channel id in config file

2018-03-10 17:14 UTC, yugecin requested changes

2018-03-10 17:14 UTC, yugecin commented on src/core/RawParser.java
> +			}
why using regex to do this?
you could just use `if (!Config.inList("igchannel", String.valueOf(p.cid)))`

2018-03-10 17:14 UTC, yugecin commented on tsstats.sample.ini
> +igclient: XXXXXXXXXXXXXXXXXXX
I'd prefer not to change existing options, to minimize the risk of existing configurations not working anymore because of a rename

2018-03-10 17:14 UTC, yugecin commented on tsstats.sample.ini
> +igchannel: X,Y,Z
`ignoredchannels` might be a better name (also update the comment above it: cid of _channels_)

2023-03-12 11:12 UTC, Loyal-Life commented
what exactly do you have to set to ignore the channels?! 
I have it with 
igchannel = id 
and 
ignoredchannels = id 

but both doesn't work that well

2023-03-12 11:13 UTC, ThatsPepe commented
what exactly do you have to set to ignore the channels?!
I have it with
igchannel = id
and
ignoredchannels = id

but both doesn't work that well

2023-03-12 20:02 UTC, yugecin commented
@ThatsPepe this change is not merged, so you can't use this unless you compile the code yourself from this commit

2023-03-12 20:09 UTC, ThatsPepe commented
> @ThatsPepe this change is not merged, so you can't use this unless you compile the code yourself from this commit

ah ok thank you very much.

is it possible to extend the code to it?

I'd be happy if you can implement it in the standard code

2025-01-11 15:03 UTC, Wunderharke commented
I happened to find this pr in my GitHub Account. It has been a while, and I am somewhat embarrassed with is one looking at it today.  I force pushed a version with aligns with your suggestions @yugecin.

2025-01-14 21:19 UTC, merged